import { Contact, Letter } from "@/types";
import { generateId } from "./id";

const now = new Date();
const iso = (d: Date) => d.toISOString().split("T")[0];
const daysAgo = (n: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() - n);
  return iso(d);
};

export function mockContacts(): Contact[] {
  return [
    {
      id: "c1",
      name: "林小雨",
      address: "北京市朝阳区建国门外大街甲6号SK大厦",
      city: "北京",
      country: "中国",
      notes: "大学室友，每周通信",
      created_at: daysAgo(180),
    },
    {
      id: "c2",
      name: "张晨阳",
      address: "上海市徐汇区衡山路10号",
      city: "上海",
      country: "中国",
      notes: "笔友，旅行爱好者",
      created_at: daysAgo(150),
    },
    {
      id: "c3",
      name: "Sophie Martin",
      address: "15 Rue de la République, 75002 Paris",
      city: "巴黎",
      country: "法国",
      notes: "法国交换生",
      created_at: daysAgo(120),
    },
    {
      id: "c4",
      name: "山本优子",
      address: "東京都渋谷区神宮前1-1-1",
      city: "东京",
      country: "日本",
      notes: "明信片交换",
      created_at: daysAgo(100),
    },
    {
      id: "c5",
      name: "王浩然",
      address: "成都市锦江区春熙路99号",
      city: "成都",
      country: "中国",
      notes: "高中同学",
      created_at: daysAgo(90),
    },
  ];
}

export function mockLetters(): Letter[] {
  const base: Letter[] = [
    {
      id: "l1",
      type: "letter",
      direction: "received",
      contact_id: "c1",
      contact_name: "林小雨",
      contact_address: "北京市朝阳区建国门外大街甲6号SK大厦",
      contact_city: "北京",
      contact_country: "中国",
      contact_latitude: 39.9042,
      contact_longitude: 116.4074,
      sent_date: daysAgo(22),
      received_date: daysAgo(19),
      stamp_value: 1.2,
      stamp_description: "故宫博物院角楼邮票",
      postmark_date: daysAgo(21),
      postmark_location: "北京建国门",
      notes: "她寄来了北京秋天的银杏叶，真美。信里说最近工作很忙。",
      is_replied: false,
      reply_to_id: null,
      photos: [],
      created_at: daysAgo(19),
      updated_at: daysAgo(19),
    },
    {
      id: "l2",
      type: "letter",
      direction: "sent",
      contact_id: "c1",
      contact_name: "林小雨",
      contact_address: "北京市朝阳区建国门外大街甲6号SK大厦",
      contact_city: "北京",
      contact_country: "中国",
      contact_latitude: 39.9042,
      contact_longitude: 116.4074,
      sent_date: daysAgo(45),
      received_date: null,
      stamp_value: 4.2,
      stamp_description: "长城风光套票",
      postmark_date: daysAgo(45),
      postmark_location: "上海外滩",
      notes: "向她介绍了我最近的工作进展，附上了外滩夜景照片。",
      is_replied: false,
      reply_to_id: null,
      photos: [],
      created_at: daysAgo(45),
      updated_at: daysAgo(45),
    },
    {
      id: "l3",
      type: "letter",
      direction: "received",
      contact_id: "c1",
      contact_name: "林小雨",
      contact_address: "北京市朝阳区建国门外大街甲6号SK大厦",
      contact_city: "北京",
      contact_country: "中国",
      contact_latitude: 39.9042,
      contact_longitude: 116.4074,
      sent_date: daysAgo(60),
      received_date: daysAgo(56),
      stamp_value: 1.2,
      stamp_description: "天坛祈年殿",
      postmark_date: daysAgo(59),
      postmark_location: "北京",
      notes: "分享了她去青海旅游的故事。",
      is_replied: true,
      reply_to_id: "l2",
      photos: [],
      created_at: daysAgo(56),
      updated_at: daysAgo(45),
    },
    {
      id: "l4",
      type: "postcard",
      direction: "received",
      contact_id: "c2",
      contact_name: "张晨阳",
      contact_address: "上海市徐汇区衡山路10号",
      contact_city: "拉萨",
      contact_country: "中国",
      contact_latitude: 29.652,
      contact_longitude: 91.1721,
      sent_date: daysAgo(8),
      received_date: daysAgo(2),
      stamp_value: 0.8,
      stamp_description: "布达拉宫纪念邮票",
      postmark_date: daysAgo(8),
      postmark_location: "拉萨八廓街",
      notes: "西藏的天空真蓝，他说下次要一起去。",
      is_replied: false,
      reply_to_id: null,
      photos: [],
      created_at: daysAgo(2),
      updated_at: daysAgo(2),
    },
    {
      id: "l5",
      type: "postcard",
      direction: "received",
      contact_id: "c3",
      contact_name: "Sophie Martin",
      contact_address: "15 Rue de la République, 75002 Paris",
      contact_city: "巴黎",
      contact_country: "法国",
      contact_latitude: 48.8566,
      contact_longitude: 2.3522,
      sent_date: daysAgo(35),
      received_date: daysAgo(15),
      stamp_value: 1.5,
      stamp_description: "La Tour Eiffel 埃菲尔铁塔邮票",
      postmark_date: daysAgo(35),
      postmark_location: "Paris Louvre",
      notes: "她寄来了卢浮宫的明信片，说蒙娜丽莎比想象中小。",
      is_replied: true,
      reply_to_id: "l6",
      photos: [],
      created_at: daysAgo(15),
      updated_at: daysAgo(12),
    },
    {
      id: "l6",
      type: "postcard",
      direction: "sent",
      contact_id: "c3",
      contact_name: "Sophie Martin",
      contact_address: "15 Rue de la République, 75002 Paris",
      contact_city: "巴黎",
      contact_country: "法国",
      contact_latitude: 48.8566,
      contact_longitude: 2.3522,
      sent_date: daysAgo(12),
      received_date: null,
      stamp_value: 18.5,
      stamp_description: "丝绸之路纪念邮票",
      postmark_date: daysAgo(12),
      postmark_location: "上海南京西路",
      notes: "回寄了苏州园林的明信片。",
      is_replied: false,
      reply_to_id: null,
      photos: [],
      created_at: daysAgo(12),
      updated_at: daysAgo(12),
    },
    {
      id: "l7",
      type: "postcard",
      direction: "sent",
      contact_id: "c4",
      contact_name: "山本优子",
      contact_address: "東京都渋谷区神宮前1-1-1",
      contact_city: "东京",
      contact_country: "日本",
      contact_latitude: 35.6762,
      contact_longitude: 139.6503,
      sent_date: daysAgo(65),
      received_date: null,
      stamp_value: 15.0,
      stamp_description: "虎年生肖邮票",
      postmark_date: daysAgo(65),
      postmark_location: "上海国际",
      notes: "寄了一张上海石库门的明信片。",
      is_replied: false,
      reply_to_id: null,
      photos: [],
      created_at: daysAgo(65),
      updated_at: daysAgo(65),
    },
    {
      id: "l8",
      type: "postcard",
      direction: "received",
      contact_id: "c4",
      contact_name: "山本优子",
      contact_address: "東京都渋谷区神宮前1-1-1",
      contact_city: "京都",
      contact_country: "日本",
      contact_latitude: 35.0116,
      contact_longitude: 135.7681,
      sent_date: daysAgo(50),
      received_date: daysAgo(40),
      stamp_value: 63,
      stamp_description: "清水寺红叶",
      postmark_date: daysAgo(49),
      postmark_location: "京都東山",
      notes: "清水寺的红叶太美了！她说下次要去岚山。",
      is_replied: false,
      reply_to_id: null,
      photos: [],
      created_at: daysAgo(40),
      updated_at: daysAgo(40),
    },
    {
      id: "l9",
      type: "letter",
      direction: "sent",
      contact_id: "c5",
      contact_name: "王浩然",
      contact_address: "成都市锦江区春熙路99号",
      contact_city: "成都",
      contact_country: "中国",
      contact_latitude: 30.5728,
      contact_longitude: 104.0668,
      sent_date: daysAgo(80),
      received_date: null,
      stamp_value: 1.2,
      stamp_description: "大熊猫邮票",
      postmark_date: daysAgo(80),
      postmark_location: "上海",
      notes: "约他暑假一起去九寨沟。",
      is_replied: false,
      reply_to_id: null,
      photos: [],
      created_at: daysAgo(80),
      updated_at: daysAgo(80),
    },
    {
      id: "l10",
      type: "letter",
      direction: "received",
      contact_id: "c5",
      contact_name: "王浩然",
      contact_address: "成都市锦江区春熙路99号",
      contact_city: "成都",
      contact_country: "中国",
      contact_latitude: 30.5728,
      contact_longitude: 104.0668,
      sent_date: daysAgo(95),
      received_date: daysAgo(88),
      stamp_value: 1.2,
      stamp_description: "三星堆文化邮票",
      postmark_date: daysAgo(94),
      postmark_location: "成都春熙",
      notes: "他说最近在准备考研，约好一起去九寨沟！",
      is_replied: true,
      reply_to_id: "l9",
      photos: [],
      created_at: daysAgo(88),
      updated_at: daysAgo(80),
    },
    {
      id: "l11",
      type: "postcard",
      direction: "received",
      contact_id: "c2",
      contact_name: "张晨阳",
      contact_address: "上海市徐汇区衡山路10号",
      contact_city: "丽江",
      contact_country: "中国",
      contact_latitude: 26.8721,
      contact_longitude: 100.2299,
      sent_date: daysAgo(110),
      received_date: daysAgo(100),
      stamp_value: 0.8,
      stamp_description: "丽江古城",
      postmark_date: daysAgo(109),
      postmark_location: "丽江大研",
      notes: "他在丽江古城寄的，说那里的夜晚很安静。",
      is_replied: false,
      reply_to_id: null,
      photos: [],
      created_at: daysAgo(100),
      updated_at: daysAgo(100),
    },
    {
      id: "l12",
      type: "letter",
      direction: "sent",
      contact_id: "c2",
      contact_name: "张晨阳",
      contact_address: "上海市徐汇区衡山路10号",
      contact_city: "上海",
      contact_country: "中国",
      contact_latitude: 31.2304,
      contact_longitude: 121.4737,
      sent_date: daysAgo(3),
      received_date: null,
      stamp_value: 1.2,
      stamp_description: "黄浦江风光",
      postmark_date: daysAgo(3),
      postmark_location: "上海外滩",
      notes: "感谢他的拉萨明信片，非常感动。",
      is_replied: false,
      reply_to_id: null,
      photos: [],
      created_at: daysAgo(3),
      updated_at: daysAgo(3),
    },
  ];

  return base.map((l) => ({
    ...l,
    id: generateId(),
  }));
}
